import Link from 'next/link';
import { ArrowUpRight, ShieldCheck, Timer, Waves } from 'lucide-react';

export default function Home() {
  return <main className="min-h-screen overflow-hidden bg-ink text-cream">
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-7"><strong className="text-xl tracking-tight">Edu<span className="text-mint">Fix</span></strong><Link className="flex items-center gap-2 rounded-full border border-cream/30 px-4 py-2 text-sm" href="/login">Sign in <ArrowUpRight size={16} /></Link></nav>
    <section className="mx-auto grid max-w-6xl gap-14 px-6 pb-20 pt-16 md:grid-cols-[1.15fr_.85fr] md:items-end md:pt-28"><div><p className="mb-6 font-medium uppercase tracking-[.24em] text-mint">Campus care, made visible</p><h1 className="max-w-3xl text-6xl font-bold leading-[.95] md:text-8xl">Every issue deserves a clear next step.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-cream/70">Report what needs attention, follow progress in real time, and help your campus teams make better decisions.</p><div className="mt-10 flex gap-3"><Link className="rounded-full bg-mint px-6 py-3 font-bold text-ink" href="/register">Create account</Link><Link className="rounded-full border border-cream/30 px-6 py-3" href="/login">Track a complaint</Link></div></div><div className="relative rounded-[2rem] bg-coral p-8 text-ink"><div className="absolute -right-8 -top-8 rounded-full bg-mint p-5"><Waves size={28} /></div><p className="text-sm font-bold uppercase tracking-widest">Live service pulse</p><p className="mt-16 text-7xl font-bold">94<span className="text-3xl">%</span></p><p className="mt-2 text-lg">of active issues are inside their SLA.</p><div className="mt-8 h-3 rounded-full bg-ink/20"><div className="h-full w-[94%] rounded-full bg-ink" /></div></div></section>
    <section className="mx-auto grid max-w-6xl gap-4 px-6 pb-16 md:grid-cols-3"><Feature icon={<Timer />} title="SLA transparency" text="Know who owns an issue and when to expect movement." /><Feature icon={<ShieldCheck />} title="Accountable routing" text="The right department sees the right problem immediately." /><Feature icon={<Waves />} title="Real-time updates" text="Get status changes without refreshing your dashboard." /></section>
  </main>;
}
function Feature({ icon, title, text }) { return <div className="border-t border-cream/20 pt-5"><div className="mb-5 text-mint">{icon}</div><h2 className="text-xl font-bold">{title}</h2><p className="mt-2 leading-6 text-cream/60">{text}</p></div>; }
