import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useAuthStore } from '../store/authStore';

export default function Register() { const router = useRouter(); const register = useAuthStore((state) => state.register); const [form, setForm] = useState({ name: '', email: '', password: '', studentId: '' }); const [error, setError] = useState(''); const update = (key) => (value) => setForm({ ...form, [key]: value });
  async function submit(event) { event.preventDefault(); setError(''); try { await register(form); router.push('/dashboard'); } catch (requestError) { setError(requestError.response?.data?.message || 'Unable to create account.'); } }
  return <AuthLayout title="Join the fix" subtitle="Create your campus account in a minute."><form onSubmit={submit} className="space-y-4"><Field label="Full name" value={form.name} onChange={update('name')} /><Field label="Student ID" value={form.studentId} onChange={update('studentId')} /><Field label="College email" type="email" value={form.email} onChange={update('email')} /><Field label="Password" type="password" value={form.password} onChange={update('password')} />{error && <p className="text-sm text-coral">{error}</p>}<button className="w-full rounded-xl bg-ink py-3 font-bold text-cream">Create account</button></form><p className="mt-6 text-center text-sm text-ink/60">Already registered? <Link className="font-bold text-ink" href="/login">Sign in</Link></p></AuthLayout>; }
function Field({ label, type = 'text', value, onChange }) { return <label className="block text-sm font-bold">{label}<input required type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-ink/15 bg-white px-4 py-3 outline-none focus:border-coral" /></label>; }
function AuthLayout({ title, subtitle, children }) { return <main className="grid min-h-screen place-items-center px-6 py-12"><div className="w-full max-w-md"><Link href="/" className="font-bold">Edu<span className="text-coral">Fix</span></Link><h1 className="mt-16 text-5xl font-bold">{title}</h1><p className="mt-3 text-ink/60">{subtitle}</p><div className="mt-8 rounded-3xl bg-white p-7 shadow-sm">{children}</div></div></main>; }
